### ISSUE TITLE
sgcc_electricity 因为页面变化失效了

### ISSUE THREAD

**Issue by SeanChengN** [dscao/hassio-addons#1]
之前一直使用dockerhub上的镜像，https://hub.docker.com/r/dscao/sgcc_electricity
最近失效了转而使用加载项，添加仓库地址后不显示selenium_electricity
![chrome_wGv859vPH0](https://github.com/dscao/hassio-addons/assets/20624068/3077e78d-93f2-4eb0-bbec-e205452e8e99)

容器日志：[_sgcc_electricity_logs.txt](https://github.com/dscao/hassio-addons/files/13176499/_sgcc_electricity_logs.txt)
类似问题：https://github.com/renhai-lab/sgcc_electricity/issues/34

**Comment by dscao** [comment]
这个与那个docker完全一样，因为登录验证变动暂时无法正常使用，临时禁用这个加载项了。

**Comment by fengshutao** [comment]
我也是，坐等大佬更新。

**Comment by fengshutao** [comment]
这个是chatgpt给的代码。
首先，确保你已经安装了相关的库：
pip install pyautogui pygetwindow

然后，可以使用以下代码：
import time
import pyautogui
import pygetwindow as gw

def find_slider_location(screenshot_path, slider_image_path):
    # 截取屏幕截图
    screenshot = pyautogui.screenshot(screenshot_path)

    # 在屏幕截图中查找滑块位置
    slider_location = pyautogui.locateOnScreen(slider_image_path, confidence=0.8)
    
    return slider_location

def simulate_slide_verification(slider_location):
    if slider_location:
        # 获取滑块中心坐标
        slider_center_x = slider_location[0] + slider_location[2] // 2
        slider_center_y = slider_location[1] + slider_location[3] // 2

        # 随机生成拖动的目标位置
        end_x = slider_center_x + 100  # 举例：向右拖动 100 像素
        end_y = slider_center_y

        # 模拟鼠标点击并按住滑块起始位置
        pyautogui.click(slider_center_x, slider_center_y)
        pyautogui.mouseDown()

        # 模拟鼠标拖动到滑块结束位置
        pyautogui.moveTo(end_x, end_y, duration=1)

        # 松开鼠标
        pyautogui.mouseUp()
    else:
        print("滑块位置未找到")

# 示例：替换为实际的文件路径
screenshot_path = "path/to/screenshot.png"
slider_image_path = "path/to/slider_image.png"

# 查找滑块位置
slider_location = find_slider_location(screenshot_path, slider_image_path)

# 调用模拟滑块验证的函数
simulate_slide_verification(slider_location)

# 延迟一段时间以观察效果
time.sleep(5)

**Comment by dscao** [comment]
参考：
https://github.com/okatu-loli/Electricity-Tracker/blob/master/scraper/slider_image_process.py

再利用 gpt，折腾了两天，代码终于跑通了

 
![image](https://github.com/dscao/hassio-addons/assets/16587914/c9d1d1a2-a50d-4c4f-826f-3b63ffbe945c)

**Comment by fengshutao** [comment]
> 参考： https://github.com/okatu-loli/Electricity-Tracker/blob/master/scraper/slider_image_process.py
> 
> 再利用 gpt，折腾了两天，代码终于跑通了
> 
> ![image](https://private-user-images.githubusercontent.com/16587914/291002078-c9d1d1a2-a50d-4c4f-826f-3b63ffbe945c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTc4MTcsIm5iZiI6MTcwMjc5NzUxNywicGF0aCI6Ii8xNjU4NzkxNC8yOTEwMDIwNzgtYzlkMWQxYTItYTUwZC00YzRmLTgyNmYtM2I2M2ZmYmU5NDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3MTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjUwN2IxMTA5ZTgzM2E1MTg0NTFhOTM1NGM1MDY5N2IwMzcxMTBmZmM1MGI0YzE0YjBlOTQzMDNiNjM0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xAtt6myqGFdSmUrVOG8Q2vpJ5RlA5n-Wgafxd7UG-IM)

大佬，什么时候更新docker镜像？

**Comment by fengshutao** [comment]
> 参考： https://github.com/okatu-loli/Electricity-Tracker/blob/master/scraper/slider_image_process.py
> 
> 再利用 gpt，折腾了两天，代码终于跑通了
> 
> ![image](https://private-user-images.githubusercontent.com/16587914/291002078-c9d1d1a2-a50d-4c4f-826f-3b63ffbe945c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTkyNzAsIm5iZiI6MTcwMjc5ODk3MCwicGF0aCI6Ii8xNjU4NzkxNC8yOTEwMDIwNzgtYzlkMWQxYTItYTUwZC00YzRmLTgyNmYtM2I2M2ZmYmU5NDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA3NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1Yjg2MzRmMTYwOWEyN2FjMjk5OTQ3MGY1OTM5NjYwNjYwNWMzZGRiZDdjN2RkN2UxM2IwYjA0NGM5MWE4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ImjYq2PNSeLZ14JcOov5fz9Qd5dYoTYew4cJiX9brok)

多重启了几次获取到数据了，感谢大佬。
![QQ图片20231217154852](https://github.com/dscao/hassio-addons/assets/69944484/c0fb8766-637e-4681-81cb-4c615ac261cc)
