### ISSUE TITLE
请问微信和国家电网的插件是不是下线了？

### ISSUE THREAD

**Issue by kylin7226** [dscao/hassio-addons#2]
请问微信和国家电网的插件是不是下线了？但是看到你的代码库中还拥有插件的代码
![image](https://github.com/dscao/hassio-addons/assets/149030808/301a13a0-fc67-4abd-8e4e-c8558ddc6cfc)

**Comment by dscao** [comment]
验证码方式改了，暂时我搞不定，等其他大老实现登录验证方法才行了。

**Comment by dscao** [comment]
关闭了
